### PR TITLE
Using gravatar photos instead of Facebook profile pics - issue #13

### PR DESCRIPTION
**Pull request by seferov**

### CODE REVIEW

**Comment by tasomaniac** [comment]
For those who don't have gravatar. Should we force them to upload their picture to gravatar? Or should we have facebook implementation as a backup if the user doesn't have gravatar?

**Comment by demircancelebi** [comment]
I guess we do not need fb_username, and photo_url fields on user model anymore, right?
@tasomaniac , I do not think we should keep fb photo as a backup but also not force anyone who does not use gravatar. We currently show a placeholder image instead of the photo, we can keep it that way.

**Comment by seferov** [comment]
@demircancelebi right, I think it is better to keep them though

**Comment by demircancelebi** [comment]
Why do you think that?

2015-07-20 17:27 GMT+03:00 Farhad Safarov notifications@github.com:

**Pull request merged**
